#!/bin/sh
# Pre-commit hook to verify no divergence between pyproject.toml and its template

difference=$(diff -y --suppress-common-lines -W300 pyproject.toml pyproject.toml.template | grep -v "<AIRFLOW_VERSION>")


if [[ -n "$difference" ]]; then
  if command -v gnome-terminal
  then
      gnome-terminal --geometry=200x100 --command "vimdiff pyproject.toml pyproject.toml.template"
  fi

  echo "Error: divergence between pyproject.toml and its template (other than <AIRFLOW_VERSION>, which is OK)"
  echo "$difference"
  exit 1
fi

exit 0
