# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: 'docs'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
# -   repo: https://github.com/pycqa/isort
#     rev: 6.0.1
#     hooks:
#     -   id: isort
#         name: isort (python)
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.11
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [--fix]
    # Run the formatter.
    - id: ruff-format
      args: [--line-length=100]
-   repo: local
    hooks:
    -   id: pyproject.toml template vs. real
        name: Making sure that pyproject.toml doesn't diverge from it's template
        description: pyproject.toml.template provides easy Airflow version management (CI for example)
        entry: bash ./.pre_commit/pyproject_toml_sync
        language: system
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
    -   id: mypy
# -   repo: https://github.com/RobertCraigie/pyright-python
#     rev: v1.1.404
#     hooks:
#     -   id: pyright
