FROM python:latest

RUN useradd -ms /bin/bash runner
USER runner

# As recommended by the Python docker container docs
WORKDIR /usr/src/runner

RUN pip install apache-airflow
RUN pip install apache-airflow-task-sdk

RUN pip install nomad

COPY src/airflow/providers/nomad /usr/src/runner/.local/lib/python3.12/site-packages/airflow/providers/nomad/ 
