FROM python:latest

RUN useradd -ms /bin/bash runner
USER runner

# As recommended by the Python docker container docs
WORKDIR /usr/src/runner

RUN pip install apache-airflow
RUN pip install apache-airflow-task-sdk

RUN pip install nomad

# To be replaced later with
# RUN pip install apache-airflow-providers-nomad
COPY . .
RUN pip install -e .
